name: Build EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install pyinstaller customtkinter pyzbar pillow opencv-python

      # Copy the DLL to the build directory
      - run: |
          mkdir -p dist/libs
          copy libs\libzbar-64.dll dist\libs\

      # Build the EXE and include the DLL
      - run: pyinstaller --onefile --add-binary "dist/libs/libzbar-64.dll;." barcode.py

      - uses: actions/upload-artifact@v4
        with:
          name: barcode
          path: dist/barcode.exe
