name: Build InbenDemo (Full Offline Runtime)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download full Python (includes Tkinter + SQLite)
        run: |
          echo Downloading Python runtime...
          curl -L -o python-installer.exe https://www.python.org/ftp/python/3.12.6/python-3.12.6-amd64.exe
          7z x python-installer.exe -opython_temp

      - name: Prepare runtime folders
        run: |
          mkdir InbenDemo
          mkdir InbenDemo\runtime
          move python_temp InbenDemo\runtime\python

      - name: Install dependencies (CustomTkinter + Pillow)
        run: |
          cd InbenDemo\runtime\python
          .\python.exe -m ensurepip
          .\python.exe -m pip install --no-cache-dir customtkinter pillow

      - name: Add your app files
        run: |
          mkdir InbenDemo\runtime\app
          xcopy app InbenDemo\runtime\app /E /I /Y

      - name: Create launcher
        run: |
          echo @echo off > InbenDemo\run_app.bat
          echo cd runtime\python >> InbenDemo\run_app.bat
          echo python.exe ..\app\demo_gui.py >> InbenDemo\run_app.bat

      - name: Verify SQLite + Tkinter work
        run: |
          cd InbenDemo\runtime\python
          .\python.exe -c "import tkinter, sqlite3; print('✅ Tkinter + SQLite OK'); conn=sqlite3.connect(':memory:'); conn.execute('CREATE TABLE test(id INT)'); conn.close()"

      - name: Package final clean build
        run: |
          7z a InbenDemo_full.zip InbenDemo

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: InbenDemo_full
          path: InbenDemo_full.zip
