name: BuildX

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create directory structure
      run: |
        mkdir InbenDemo
        mkdir InbenDemo\runtime
        mkdir InbenDemo\runtime\python
        mkdir InbenDemo\runtime\app

    - name: Download Portable Python
      run: |
        cd InbenDemo\runtime\python
        curl -L -o python-portable.zip https://github.com/indygreg/python-build-standalone/releases/download/20231002/cpython-3.11.6+20231002-x86_64-pc-windows-msvc-shared-install_only.tar.gz
        tar -xzf python-portable.zip --strip-components=1
        del python-portable.zip

    - name: Add demo GUI script
      run: |
        echo import tkinter as tk > InbenDemo\runtime\app\demo_gui.py
        echo root = tk.Tk() >> InbenDemo\runtime\app\demo_gui.py
        echo root.title("Inben Demo") >> InbenDemo\runtime\app\demo_gui.py
        echo tk.Label(root, text="✅ Offline Runtime Test Successful!").pack(padx=30, pady=30) >> InbenDemo\runtime\app\demo_gui.py
        echo root.mainloop() >> InbenDemo\runtime\app\demo_gui.py

    - name: Add bootstrap launcher
      run: |
        echo @echo off > InbenDemo\bootstrap.bat
        echo cd runtime\python >> InbenDemo\bootstrap.bat
        echo python.exe ../app/demo_gui.py >> InbenDemo\bootstrap.bat

    - name: Verify Python setup
      run: |
        cd InbenDemo\runtime\python
        dir python.exe
        if not exist python.exe exit /b 1

    - name: Package folder
      run: |
        7z a InbenDemo_full.zip InbenDemo >nul
        dir InbenDemo_full.zip

    - name: Upload ZIP Artifact
      uses: actions/upload-artifact@v4
      with:
        name: InbenDemo_Full_Runtime
        path: ./InbenDemo_full.zip
