name: Build Barcode Scanner EXE

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [win32, x64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Determine version
        id: version
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "VERSION=1.0.$COMMIT_COUNT" >> $GITHUB_ENV
          echo "Built version: $VERSION"

      - name: Build EXE
        run: |
          echo "Building for ${{ matrix.arch }}"
          if [ "${{ matrix.arch }}" == "win32" ]; then
            PYINSTALLER_ARGS="--onefile --windowed --name barcode_scanner_32"
          else
            PYINSTALLER_ARGS="--onefile --windowed --name barcode_scanner_64"
          fi
          pyinstaller $PYINSTALLER_ARGS barcode_scanner.py
        continue-on-error: true   # <-- important: build failure won't cancel the workflow

      - name: Upload artifacts
        if: always()   # <-- upload whatever was built
        uses: actions/upload-artifact@v4
        with:
          name: barcode-scanner-${{ matrix.arch }}-v${{ env.VERSION }}
          path: dist/*
